### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by mornir** [Grsmto/sanity-plugin-mapbox-input#1]
Hi!
Thanks for this package!

I installed it via `sanity install mapbox-input` then I added my API key, but when I run `sanity start`, I get errors about unfound files.

What did I do wrong?

**Comment by Grsmto** [comment]
Hey,
Can you give more details? What is the error you're having?

**Comment by mornir** [comment]
I installed it on freshly created Sanity project: https://github.com/mornir/mapbox-test
And I get that error. (I did set up a valid API key)
`Error in ./node_modules/sanity-plugin-mapbox-input/lib/GeopointSelect.js
Module not found: Error: Can't resolve 'react-map-gl-geocoder/dist/mapbox-gl-geocoder.css?raw' in 'C:\projects\mapbox\node_modules\sanity-plugin-mapbox-input\lib'
 @ ./node_modules/sanity-plugin-mapbox-input/lib/GeopointSelect.js 10:0-64
 @ ./node_modules/sanity-plugin-mapbox-input/lib/GeopointInput.js (part:@sanity/form-builder/input/geopoint)    
 @ ./node_modules/@sanity/form-builder/lib/sanity/inputResolver/customInputs.js
 @ ./node_modules/@sanity/form-builder/lib/sanity/inputResolver/inputResolver.js
 @ ./node_modules/@sanity/form-builder/lib/sanity/SanityFormBuilderContext.js
 @ ./node_modules/@sanity/form-builder/lib/sanity (part:@sanity/form-builder)
 @ ./node_modules/@sanity/desk-tool/lib/pane/Editor/HistoryForm.js
 @ ./node_modules/@sanity/desk-tool/lib/pane/Editor/FormView.js
 @ ./node_modules/@sanity/desk-tool/lib/pane/DocumentPane.js
 @ ./node_modules/@sanity/desk-tool/lib/pane/DocumentPaneProvider.js
 @ ./node_modules/@sanity/desk-tool/lib/pane/Pane.js
 @ ./node_modules/@sanity/desk-tool/lib/DeskToolPanes.js
 @ ./node_modules/@sanity/desk-tool/lib/DeskTool.js
 @ ./node_modules/@sanity/desk-tool/lib/tool.js
 @ ./node_modules/@sanity/vision/lib/VisionTool.js (all:part:@sanity/base/tool)
 @ ./node_modules/@sanity/default-layout/lib/defaultLayoutRouter.js
 @ ./node_modules/@sanity/default-layout/lib/components/DefaultLayoutContainer.js (part:@sanity/base/root)      
 @ ./node_modules/@sanity/base/lib/components/SanityRoot.js (part:@sanity/base/sanity-root)
 @ ./node_modules/@sanity/server/lib/browser/entry-dev.js
 @ multi ./node_modules/normalize.css/normalize.css ./node_modules/@sanity/server/lib/browser/entry-dev.js      `

**Comment by Grsmto** [comment]
I just released a new version `0.0.2` could you try again?

**Comment by mornir** [comment]
Thanks for the quick update 🙂
I get this error now:
`Error in ./node_modules/@sanity/form-builder/lib/sanity/inputResolver/customInputs.customInputs.js
Module not found: Error: Can't resolve 'part:@sanity/form-builder/input/geopoint?' t/geopoint?' in 'C:\projects\mapbox\node_modules\@sanity\form-builder\putResolver' lib\sanity\inputResolver' @ ./node_modules/@sanity/form-builder/lib/sanputs.js 14:3nity/inputResolver/customInputs.js 14:39-91
 @ ./node_modules/@sanity/form-builder/lib/sanity/inputResolver/inputResolver.js   esolver.js                                                            text.js      
 @ ./node_modules/@sanity/form-builder/lib/sanity/SanityFormBuilderConuilder)      text.js
 @ ./node_modules/@sanity/form-builder/lib/sanity (part:@sanity/form-builder)
 @ ./node_modules/@sanity/desk-tool/lib/components/BrokenReferences.js
 @ ./node_modules/@sanity/desk-tool/lib/utils/withInitialValue.js     
 @ ./node_modules/@sanity/desk-tool/lib/pane/DocumentPaneProvider.js  
 @ ./node_modules/@sanity/desk-tool/lib/pane/Pane.js                  ase/tool)    
 @ ./node_modules/@sanity/desk-tool/lib/DeskToolPanes.js
 @ ./node_modules/@sanity/desk-tool/lib/DeskTool.js                   ontainer.js (
 @ ./node_modules/@sanity/desk-tool/lib/tool.js
 @ ./node_modules/@sanity/vision/lib/VisionTool.js (all:part:@sanity/bity/base/saniase/tool)
 @ ./node_modules/@sanity/default-layout/lib/defaultLayoutRouter.js   
 @ ./node_modules/@sanity/default-layout/lib/components/DefaultLayoutCnity/server/lontainer.js (part:@sanity/base/root)
 @ ./node_modules/@sanity/base/lib/components/SanityRoot.js (part:@sanity/base/sanity-root)
 @ ./node_modules/@sanity/server/lib/browser/entry-dev.js
 @ multi ./node_modules/normalize.css/normalize.css ./node_modules/@sanity/server/lib/browser/entry-dev.js`

Is this package supposed to work with the `sanity install` command?

**Comment by Ojay** [comment]
Yeah I'm running into the same issue...
`Error in ./node_modules/@sanity/form-builder/lib/sanity/inputResolver/customInputs.js
Module not found: Error: Can't resolve 'part:@sanity/form-builder/input/geopoint?'`

**Comment by Grsmto** [comment]
Sorry about that guys, it was quite and odd bug. Should be fixed in the latest version.
