### ISSUE TITLE
Unclear init

### ISSUE THREAD

**Issue by jedifunk** [Grsmto/sanity-plugin-mapbox-input#7]
The README leaves a lot to be desired.

I'd like to use this plugin, but you truly give no useable details.

I've run sanity install, but trying to use your example results in an error of:
`Module not found: Error: Part "part:@sanity/base/bundled-types" not implemented by any plugins`

Could you please provide more details on how to install and set this plugin up? Thanks.

**Comment by Grsmto** [comment]
Hey,
Thanks for your feedback.
You should be able to install the plugin with the Sanity CLI: 
`sanity install mapbox-input`

and then follow the instruction about the Mapbox token in the README and that should work.

The example in the repo is outdated, I'll take care of it.

**Comment by jedifunk** [comment]
And then what? I guess that's what I'm saying ... there's no details on HOW to use this plugin, how to implement it.

I have it installed, and have updated my config with my apiKey ... but then what? How does it work?

**Comment by Grsmto** [comment]
Ok I didn't get what you meant in your first message.
This plugin replaces the native Sanity `geopoint` type by a Mapbox map.
So wherever you use the `geopoint` type in your Sanity schema  it will appear. As in the following example schema:

```
export default {
  name: 'article',
  title: 'Article',
  type: 'document',
  fields: [
    {
      name: 'location',
      type: 'geopoint',
      title: 'Location',
    },
  ],
}

```

**Comment by jedifunk** [comment]
Ok, then it's not working for me.

here's my schema
`export default {
  title: "Places",
  name: "place",
  type: "document",
  icon: Pin,
  fields: [
    {
      title: "Name",
      name: "name",
      type: "string"
    },
    {
      title: "Address",
      name: "address",
      type: "string"
    },
    {
      title: "City",
      name: "city",
      type: 'reference',
      to: [{type: 'city'}]
    },
    {
      title: "Country",
      name: "country",
      type: "reference",
      to: [{type: 'country'}]
    },
    {
      title: "Geo",
      name: "geo",
      type: "geopoint"
    },`

**Comment by jedifunk** [comment]
Ok, not sure what was going on but its working now... thank you for updating the README and editing the example. This is going to be a very well used plugin for me!
